//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping
    {
        public int ShippingID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string ShippingMethod { get; set; }
        public string ShippingStatus { get; set; }
        public Nullable<System.DateTime> EstimatedDelivery { get; set; }
        public Nullable<System.DateTime> ActualDelivery { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
